### ISSUE TITLE
Define dd

### ISSUE THREAD

**Issue by Manojkl** [AshAswin/Adaptive-Deployment-of-Safety-Monitors-of-Autonomous-Systems#8]
https://github.com/AshAswin/Adaptive-Deployment-of-Safety-Monitors-of-Autonomous-Systems/blob/38b7540a85d0ab644a080bf2d9ab2845a2c37e5d/platforms.mzn#L23

Please define dd inside the platforms.mzn file to make python integration work.

**Comment by AshAswin** [comment]
Addressed in #10
